3414 fix dispo statuscode and statecode
NYCPlanning/labs-zap-search pull request #1354
Opened 2021-06-14 18:56 UTC by dhochbaum-dcp

### Summary
Fixes issue where disposition statuscodes and statecodes were set to incorrect values on the front-end.

#### Tasks/Bug Numbers
 - Fixes AB#3414
 
### Technical Explanation
Removes complex logic to figure out the statuscode and statecode which wasn't working, and simply uses the values that we already received from the server.

### Any other info you think would help a reviewer understand this PR?

2021-06-14 19:16 UTC, allthesignals requested changes
@godfreyyeung can you take a look at this as well?

Let's huddle and figure out what the issue is. We want to preserve the LUP-side behavior while also addressing the issue you're trying to fix.

2021-06-14 19:16 UTC, allthesignals commented on client/app/models/disposition.js
> -  get statuscode() {
I'm pretty concerned about removing this logic because of how it might affect the LUP side of things

2021-06-14 19:16 UTC, allthesignals commented on client/tests/unit/models/disposition-test.js
> -  test('when participant opts out/submits, statuscode becomes "saved"/"submitted"', async function(assert) {
Hmm unless there's a good reason we should not be deleting tests in order to get the suite to pass. These are our only defense against regressions (read: grumpy emails).

2021-06-15 15:21 UTC, godfreyyeung commented
> @godfreyyeung can you take a look at this as well?
> 
> Let's huddle and figure out what the issue is. We want to preserve the LUP-side behavior while also addressing the issue you're trying to fix.

We should meet with komal/liz/aline to see if it's still appropriate to derive statuscode and statecode on the frontend. I think it is better to read the value directly from the backend as it's less buggy. I don't remember context/pertinence of those frontend statuscode and statecode computed attributes.

2021-06-16 17:46 UTC, dhochbaum-dcp commented
We have agreed to move forward with using the data directly from CRM, as implemented above.

2021-06-16 17:46 UTC, merged